### ISSUE TITLE
Make the landing page more responsive

### ISSUE THREAD

**Issue by banta** [nairuby/arc_platform#20]

**Comment by W3NDO** [comment]
What would be the requirements for this? 
Do we have any figma templates for how the target UI should look like?

**Comment by JudahSan** [comment]
Here’s the [original design](https://still-snowflake-8822.animaapp.io/). The home page, navbar, and footer have recently been updated. I’m closing the issue, but feel free to open a new one if you think there's anything else that could be improved or added.
