### ISSUE TITLE
Deploy to fly.io

### ISSUE THREAD

**Issue by kamalogudah** [nairuby/arc_platform#23]
We need to deploy to fly.io its like the old heroku but much better. https://fly.io/

**Comment by denissellu** [comment]
@banta & I spoke and have create an account to begin experiementing with this

**Comment by banta** [comment]
Hi @denissellu, how far are you with this?

**Comment by denissellu** [comment]
an update

https://community.fly.io/t/rails-fly-toml-file-generated-look-wrong-or-incomplete-with-redis-error/11699

i've been having issues with the steps provided on their docs, i've reached out to their community, maybe i'm missing something
