### ISSUE TITLE
Add the landing page

### ISSUE THREAD

**Issue by kamalogudah** [nairuby/arc_platform#3]
Create a landing page controller that will serve an index page which will form our landing page as shown in [mock landing page](https://still-snowflake-8822.animaapp.io/) on this ticket just add the controller and the template with a place holder content.

**Comment by banta** [comment]
This is done. See the screenshot below.

<img width="1429" alt="image" src="https://user-images.githubusercontent.com/668742/210289232-c4f8d595-15b8-4697-a2d6-799a26b54455.png">
