### ISSUE TITLE
[Proposal] Replace RVM & rbenv with asdf

### ISSUE THREAD

**Issue by denissellu** [nairuby/arc_platform#45]
[asdf](https://github.com/asdf-vm/asdf) is kinda like rbenv, but the main advantage is that it is able to manage not just Ruby versions, but also Node.js, Python, and many more via its plugin architecture. Porjects naturally eveolve to be many languages, even Rails comes with Node.js, why keep separate version manager for each language? 

Website: [asdf github](https://github.com/asdf-vm/asdf)
Website: [asdf website](https://asdf-vm.com/)

if you agree, I can create a PR and add basic steps for people to start using it, I personally recommend it for any project you are working on!

@banta @kamalogudah thoughts??

**Comment by banta** [comment]
I like it. Let's go with it. @kamalogudah, what do you think?
