### ISSUE TITLE
Add cancancan for Authorization

### ISSUE THREAD

**Issue by kamalogudah** [nairuby/arc_platform#5]
We need to setup cancancan for our authorization  [more information on installation](https://github.com/CanCanCommunity/cancancan)

**Comment by AndrewNduati** [comment]
Group Two members.
@karvel_code
@Joylorrine
@newtonmutugi

Thur 14-07

We want to build our knowledge on:

1. Ruby on Rails
2. CanCanCan

**Comment by AndrewNduati** [comment]
Greetings!
@karvel-code
@Joylorrine
@NewtonMutugi

Pole kwa kuwa MIA. How are we doing? :)

**Comment by NewtonMutugi** [comment]
Hi @AndrewNduati,
I was able to fork the repo, had some issues with starting the server but fortunately I was able to fix them. I have also noticed that not much has been done (including the models) so I don't know what the way forward is.

**Comment by AndrewNduati** [comment]
@NewtonMutugi How about we begin with modelling based on the [database designs shared](https://dbdiagram.io/d/62afab7c9921fe2a96397c1e) here? 

I'm happy to guide you through and work on it together.

**Comment by NewtonMutugi** [comment]
@AndrewNduati Yes that is a good idea.

**Comment by AndrewNduati** [comment]
Hey @NewtonMutugi , 

Have you made any progress thus far?
Need help anywhere
