### ISSUE TITLE
Improve the styling of the header and footer section using semantic UI

### ISSUE THREAD

**Issue by Wesley-waka** [nairuby/arc_platform#63]

**Comment by banta** [comment]
Hello @Wesley-waka, thank you for submitting the issue. However, we use the https://tailwindcss.com/ framework for our UI design. It would be greatly appreciated if you could utilize this framework to enhance the UI.

**Comment by Wesley-waka** [comment]
Yeah I'm also eloquent in tailwind it would be great if I style the header and footer section.

**Comment by Wesley-waka** [comment]
Thanks I'll be on it I'll update you once I'm done.

**Comment by banta** [comment]
Cool beans 👍

**Comment by Wesley-waka** [comment]
kindly review the pull request I have opened.Thank you.
