### ISSUE TITLE
Create develop branch

### ISSUE THREAD

**Issue by kamalogudah** [nairuby/arc_platform#64]
We need to add a develop branch to avoid merging directly to the main branch, this will limit the chances of main /production breaking in the event of a bad deployment.
With this change, all PRs will pull against develop and not main.
WDYT @banta

**Comment by banta** [comment]
Hi @kamalogudah, develop branch is necessary when
- there is a staging or sandbox environment
- there is UAT process

I feel when the two above are not there, it becomes redundant.
