### ISSUE TITLE
[Proposal] Delegating resource CRUD to Motor Admin

### ISSUE THREAD

**Issue by denissellu** [nairuby/arc_platform#70]
Would it be beneficial to delegate the CRUD operations for managing `Chapters`, `Countries`, and `Projects` to Motor Admin? By doing so, we can eliminate the need for dedicated CRUD endpoints and methods for these resources, reducing maintenance, minimized confusion, and potentially a lighter workload.

I'm suggesting this change mainly because currently, the Chapters admins do not have any specific actions related to their role. All the resource creation (as far as I can see) is handled by the organization admins, who can do so through Motor Admin.

Please let me know your thoughts on this

cc @banta

**Comment by banta** [comment]
@denissellu, I agree. We can eliminate the dedicated CRUD endpoints and methods for Chapters, Countries, and Projects since it's already handled by Motor Admin. Let's go ahead and make the required changes.

**Comment by denissellu** [comment]
@banta i have a PR ready here https://github.com/nairuby/arc_platform/pull/72 have a look and let me know what you think

**Comment by banta** [comment]
@denissellu, I've reviewed and merged PR #72. Thank you for your contribution.

**Comment by denissellu** [comment]
great, thanks
